### ISSUE TITLE
Support for different species

### ISSUE THREAD

**Issue by kuzirh** [crowelab/PyIR#15]
https://github.com/crowelab/PyIR/blob/1a4d9b851f6dc99aa64744be4091cd144b41a568/pyir/arg_parse.py#L175

Hello I am looking to run PYir on mice, but as I was going through the code I noticed that mouse is no longer an option that can passed into the tool. Is this something done intentional, or does this tool not work on mice anymore?

Thanks,

- Kuzirh

**Comment by dwightkuo** [comment]
Along the same lines, I'm trying to use a custom set of V-genes and it isn't obvious how to do this with PyIR. There's the --germlineV option but when I use this with my custom FASTA file I get no results.

**Comment by dwightkuo** [comment]
I think I figured it out, I needed to create a BLAST database with the following options:
pyir/data/bin/makeblastdb_darwin -in imgt.V.dna.fa -input_type fasta -dbtype nucl  -hash_index -parse_seqids

I would think you could do the same for the V, D, J for mouse, etc...

**Comment by kuzirh** [comment]
@dwightkuo Yeah I thought about doing the same thing. Thanks for the confirmation on that. I am going to go ahead and close the issue 👍

**Comment by crowelab** [comment]
Thanks for the help @dwightkuo ! Yeah if you build your own custom databases with the makeblastdb executable you can pass them in with the --germlineV/J/D arguments.

Also, @kuzirh, theoretically yes, all you need to do is uncomment out that line and you should be able to process mouse sequences as well. It's not officially supported by us just because our lab works almost exclusively with human sequences so it was an extra level of functionality/testing that we didn't want to commit to, but the underlying code to make it work is all there and even a part of the SetupGermlineLibrary.sh script.

I did have someone message me in June about errors with the mouse germline databases automatically building due to incorrect formatting of the .fasta files from IMGT, I don't know if those ever got fixed but if they did running SetupGermlineLibrary.sh should give you a set of mouse databases to use (and if it didn't lines 53-70 of the script shows you the sources it's grabbing)
