### ISSUE TITLE
Failure in building docker image

### ISSUE THREAD

**Issue by jeremyadamsfisher** [crowelab/PyIR#3]
When building the docker image, the Ig tests fails with what looks to be an improperly written regex:
```bash
Starting process pool using 4 processors
 22%|██▏       | 108/500 [00:00<00:03, 109.25seq/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/pyir/igblast.py", line 20, in run
    return igblast_run.run_single_process(fasta_input_file, fastq_input_file)
  File "/usr/local/lib/python3.7/site-packages/pyir/igblast.py", line 144, in run_single_process
    total_parsed = parser.parse()
  File "/usr/local/lib/python3.7/site-packages/pyir/parsers.py", line 615, in parse
    self.output = parser.parse(line, self.output, previous_line_whitespace, self.seq_dict)
  File "/usr/local/lib/python3.7/site-packages/pyir/parsers.py", line 92, in parse
    self.hits.append({'gene': matches.group(1), 'bit_score': float(matches.group(2)), 'e_value':float(matches.group(3))})
ValueError: could not convert string to float: 'sapiens|IGHV8|P|V-REGION'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pyir", line 14, in <module>
    py_ir.run()
  File "/usr/local/lib/python3.7/site-packages/pyir/factory.py", line 65, in run
    output_pieces = self.run_pool(input_pieces, fastq_input_pieces, total_seqs)
  File "/usr/local/lib/python3.7/site-packages/pyir/factory.py", line 218, in run_pool
    for x in imap:
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: could not convert string to float: 'sapiens|IGHV8|P|V-REGION'
```

**Comment by tjonesster** [comment]
This issue should be sorted out. 
It was happening because there were 2 Genes in IMGT's IGHV.fasta file which had a different naming convention from the others. 

There are 3 changes which have been made to account for this.

1. Sam Schmitz pushed a fix which would allow for us to have spaces in gene names.
2. IMGT has changed the naming of the last 2 genes in IGHV.fasta to the standard.
3. I edited the regex in the edit_imgt_file.pl file so that it would match properly with the new naming scheme that they were using as well as the standard one. 


EDIT: I decided to revert change number 3 since they are sticking to the old naming convention. Here are some more details about what the issue was in case something similar happens in the future and needs to be fixed.
Notes about change number 3

old perl regex 
if ($line =~ /^>.*\|(IG.+)\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|.*\|$/){

old standard format
>AB019437|IGHV7-81*01|Homo sapiens|ORF|V-REGION|6456..6751|296 nt|1| | | | |296+24=320| | |

the 2 exceptions to the naming convention which were present prior to the most recent release 
>AB019438|Homsap_IGHV8-51-1*01|Homo sapiens|IGHV8|P|V-REGION
>IMGT000035|Homsap_IGHV8-51-1*02|Homo sapiens|IGHV8|ORF|V-REGIO

new perl regex line 

if ($line =~ /^>[\w\d\-\*\\\/\(\)\@\!\`\~\#\$\%\^\&]*\|(Homsap_)?(IG[\w\d\-\*\/\\\(\)\&\^\%\$\#\@\!\~\`]+)\|((.*)?\|?)*/ )

The issue with the old regex was that the . symbol could match any symbol including |. in order to get around this issue the perl script was assuming that there would be a set number of vertical bars in the description. 
When this convention was not upheld it had issues.
In order to get around this I had to remove the .* from the first regex and replace it with a set of symbols that could match with anything except |. This made it so that we did not have to have a set number of | symbols following the gene name in order for the file to be parsed correctly. 

My regex change will no longer be needed since they other files that we are using to build the germline reference blast database have been changed.


Please let me know if you have any questions

**Comment by jeremyadamsfisher** [comment]
Excellent, this is working great. Thank you!
